### ISSUE TITLE
The new version app doesn't work when install success.

### ISSUE THREAD

**Issue by liqi1997** [leanflutter/auto_updater#10]
![图片](https://user-images.githubusercontent.com/79690599/162390446-eb2790f4-4be6-466b-a82a-3e07ffeb6969.png)
![图片](https://user-images.githubusercontent.com/79690599/162390403-3463ad3b-7506-41fd-8cd2-990c39c1b7fc.png)

I finished all of steps, but the page is also old.

The new version created by `flutter build windows`, is it has problems?

**Comment by lijy91** [comment]
Please make sure the version number of `Runner.rc` has been modified correctly

https://github.com/leanflutter/auto_updater/blob/028c2b61942f9cbaf8e74257036362f44b3bf6aa/example/windows/runner/Runner.rc#L66

**Comment by liqi1997** [comment]
I use flutter_distrubutor to create setup.exe and successfully install new version. Thanks!
