### ISSUE TITLE
Error. 

### ISSUE THREAD

**Issue by yusifahmadov** [leanflutter/auto_updater#15]
Cannot open file, path = 'windows/packaging/exe/make_config.yaml' (OS Error: The system cannot find the path specified.

when run flutter_distributor release --name dev --jobs release-windows

**Comment by lijy91** [comment]
Please create the make_config.yaml file according to the documentation
https://distributor.leanflutter.org/docs/makers/exe

**Comment by yusifahmadov** [comment]
> Please create the make_config.yaml file according to the documentation https://distributor.leanflutter.org/docs/makers/exe

how can i get my unique app id?

**Comment by lijy91** [comment]
> > Please create the make_config.yaml file according to the documentation https://distributor.leanflutter.org/docs/makers/exe
> 
> how can i get my unique app id?

It's a GUID, you can generate one with the guid generator

**Comment by yusifahmadov** [comment]
> > > Please create the make_config.yaml file according to the documentation https://distributor.leanflutter.org/docs/makers/exe
> > 
> > 
> > how can i get my unique app id?
> 
> It's a GUID, you can generate one with the guid generator

Yeap, i did everything that you say. But when i open the my application and i click the install new version, i get a error like this "an error occured in retrieving update information; are you connected to the internet? Please try again later"

**Comment by lijy91** [comment]
1. Make sure the url attribute of the enclosure node is a correct link (recommended to include hostname)
2. Make sure the signature's property name and value are correct, `sparkle:edSignature` for macOS and `sparkle:dsaSignature` for Windows.

**Comment by yusifahmadov** [comment]
can you give a example appcast.xml that is real? Because i am confused where i have to add something

**Comment by lijy91** [comment]
See sparkle and winsparkle for documentation and examples of appcast.xml.

https://github.com/sparkle-project/Sparkle/blob/2.x/Resources/SampleAppcast.xml
https://github.com/vslavik/winsparkle/wiki/Appcast-Feeds

**Comment by yusifahmadov** [comment]
Thanks a lot. İ did.👍
