### ISSUE TITLE
Possible to use with msix?

### ISSUE THREAD

**Issue by ollydixon** [leanflutter/auto_updater#17]
We https://pub.dev/packages/msix to package our app. Using exe doesn't really work because of package DLL's.

Is it possible to use this updater with msix?

**Comment by lijy91** [comment]
I can't find out if it supports msix in winsparkle repo. maybe you can give it a try.

https://github.com/vslavik/winsparkle/wiki/Appcast-Feeds#installer-arguments

**Comment by ollydixon** [comment]
@lijy91 I'm using INNO script instead, works great.
