### ISSUE TITLE
[Windows] The app just closes when it says 'install update'

### ISSUE THREAD

**Issue by ollydixon** [leanflutter/auto_updater#18]
**Below**

**Comment by ollydixon** [comment]
For anyone else that's stuck on this, you can use INNO 6. It works great on release :-)

**Comment by lijy91** [comment]
winsparkle may not support msix

**Comment by lijy91** [comment]
https://github.com/vslavik/winsparkle/wiki/Appcast-Feeds#installer-arguments

Please use inno setup or nsis package
