### ISSUE TITLE
Using the same private key on a different machine breaks

### ISSUE THREAD

**Issue by ollydixon** [leanflutter/auto_updater#20]
<img width="565" alt="Screenshot 2022-06-19 at 11 04 13" src="https://user-images.githubusercontent.com/6940726/174473655-d3a19423-2617-4150-a26d-8411e52025c8.png">

Cannot upload from a new machine since the private key generated doesn't work.

**Comment by ollydixon** [comment]
For anyone else who is stuck. The auto-updater doesn't work. Also importing manually via UI does not work.

You need to manually import using command line.
# security import /Users/oliverdixon/Projects/bap/flutter/dsa_priv.pem -k ~/Library/Keychains/login.keychain
# security import /Users/oliverdixon/Projects/bap/flutter/dsa_pub.pem -k ~/Library/Keychains/login.keychain

@lijy91 would be great to add this to the docs.

**Comment by daverin** [comment]
I'm not following. There is no dsa_priv.pem and dsa_pub.pem on macOS?
