### ISSUE TITLE
The executable requests the com.apple.security.get-task-allow entitlement.

### ISSUE THREAD

**Issue by ollydixon** [leanflutter/auto_updater#21]
When trying to notorise the app with ``xcrun altool --notarize-app --primary-bundle-id "com.myApp.app" --username "---" --password "---" --file myApp.app``

We get the following errors back from Apple, any ideas how we can fix this?

<img width="1427" alt="Screenshot 2022-06-19 at 16 46 09" src="https://user-images.githubusercontent.com/6940726/174486824-baf5837a-fbdd-48a8-9b57-189008467315.png">

**Comment by ollydixon** [comment]
Without notarization users cannot install the app.

**Comment by ollydixon** [comment]
Setting this to no fixes it. Have not tested the update yet.

<img width="550" alt="Screenshot 2022-06-19 at 16 55 24" src="https://user-images.githubusercontent.com/6940726/174487198-def60a02-eb9a-452b-bc53-8930c5819ebe.png">

**Comment by ollydixon** [comment]
After disabling this setting the automatic update fails.

<img width="298" alt="Screenshot 2022-06-19 at 17 06 39" src="https://user-images.githubusercontent.com/6940726/174487683-2eabf2d2-7d8a-4857-a9ef-19d1e152998c.png">

**Comment by ollydixon** [comment]
For anyone else who is stuck, you have to add the following build steps.

```
# Sign Sparkle https://sparkle-project.org/documentation/sandboxing/
CODE_SIGN_IDENTITY="Developer ID Application: [you developer id]"
codesign -f -s "$CODE_SIGN_IDENTITY" -o runtime ${build_loc}my-app.app/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/org.sparkle-project.InstallerLauncher.xpc
codesign -f -s "$CODE_SIGN_IDENTITY" -o runtime --entitlements Entitlements/org.sparkle-project.Downloader.entitlements ${build_loc}my-app.app/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/org.sparkle-project.Downloader.xpc
codesign -f -s "$CODE_SIGN_IDENTITY" -o runtime ${build_loc}my-app.app/Contents/Frameworks/Sparkle.framework/Versions/B/Autoupdate
codesign -f -s "$CODE_SIGN_IDENTITY" -o runtime ${build_loc}my-app.app/Contents/Frameworks/Sparkle.framework/Versions/B/Updater.app
codesign -f -s "$CODE_SIGN_IDENTITY" -o runtime ${build_loc}my-app.app/Contents/Frameworks/Sparkle.framework
```

**Comment by ollydixon** [comment]
@lijy91 might be good to have some docs on this.

**Comment by jzau** [comment]
I had the similar issue, in my case it was different sparkle files that cause the notarize issue. What i did was signing the whole Sparkle framework using `--deep` before exporting the app so that we don't have to resign our own app. 

`codesign -f -s "$CODE_SIGN_IDENTITY" -o runtime --deep Pods/Sparkle/Sparkle.framework/
`
