### ISSUE TITLE
macOS build error

### ISSUE THREAD

**Issue by q7w8e9123456** [leanflutter/auto_updater#3]
I am try to build macOS but I got error,i don't know why,i am sure has add EdDSA key in Info.plist and add flutter_distributor library

this is my error:
Unhandled exception:
ProcessException: No such file or directory
  Command: 7z a dist/1.0.0+1/annual_party_guest_draw-1.0.0+1-macos.zip ./build/macos/Build/Products/Release/*.app
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      AppPackageMakerZip.make (package:app_package_maker_zip/src/app_package_maker_zip.dart:36:15)
<asynchronous suspension>

I already check in ./build/macos/Build/Products/Release has built out app file, so I don't know why error

**Comment by lijy91** [comment]
Make sure 7zip is installed

https://distributor.leanflutter.org/configuration/makers/zip
