### ISSUE TITLE
flutter pub run auto_updater:generate_keys  Error

### ISSUE THREAD

**Issue by IOCloudFly** [leanflutter/auto_updater#37]
I don't know

![Uploading 1111.png…]()

**Comment by zmbeex** [comment]
dart pub global activate flutter_distributor
flutter pub run auto_updater:generate_keys

**Comment by felixwoestmann** [comment]
I also added 
`pod 'Sparkle' `
to my Podfile (building for macOS). That did the trick.

**Comment by lijy91** [comment]
Please update to 0.1.7
