### ISSUE TITLE
Why is the signing output two lines? Do I need to merge them?

### ISSUE THREAD

**Issue by novas1r1** [leanflutter/auto_updater#38]
Hey,
I have a maybe stupid question, but when I'm signing my windows build I'm getting two lines for the signature. When I'm putting them into my `appcast.xml` file - do I need to separate them somehow or just merge them together? The example here also shows two lines, but not how/if to merge them. If they need to be merged: what reason is there for putting them in separate lines?

![image](https://user-images.githubusercontent.com/2575205/220443014-c957f695-405b-4844-80b7-761b92a731ea.png)

Thanks in advance!

**Comment by lijy91** [comment]
Yes please merge it on one line
