### ISSUE TITLE
【Windows】WinSparkle.lib 目录定位错误 

### ISSUE THREAD

**Issue by 15563988825** [leanflutter/auto_updater#4]
WinSparkle.lib 文件位置定位错误（可能是32位兼容问题？）

**报错路径**：D:\WORKSPACE\Flutter\windows\flutter\ephemeral.plugin_symlinks\auto_updater\windows\WinSparkle-0.7.0\x64\Release
**正确路径**：D:\WORKSPACE\Flutter\windows\flutter\ephemeral.plugin_symlinks\auto_updater\windows\WinSparkle-0.7.0\Release

**错误信息：**
“D:\WORKSPACE\Flutter\build\windows\plugins\auto_updater\auto_updater_plugin.vcxproj”(默认目标) (4) ->
[ ] (Link 目标) ->
[ ] 0 个警告
[ ] 1 个错误
[ ] 已用时间 00:00:25.45
[ ] LINK : fatal error LNK1104: 无法打开文件“D:\WORKSPACE\Flutter\windows\flutter\ephemeral.plugin_symlinks\auto_updater\windows\WinSparkle-0.7.0\x64\Release\WinSparkle.lib” [D:\WORKSPACE\Flutter\build\windows\plugins\auto_updater\auto_updater_plugin.vcxproj]
![160226404-8ef1b038-3a5a-4d0d-a8a8-6de0f4fac383](https://user-images.githubusercontent.com/4360198/160226545-189932a7-409f-42ba-9fcf-85cf6093f3bc.png)

**Comment by lijy91** [comment]
已修复，请更新到 0.1.3
