### ISSUE TITLE
Not working autoupdate

### ISSUE THREAD

**Issue by kekko7072** [leanflutter/auto_updater#41]
I have created this app to manage links and code snippets.
[https://github.com/kekko7072/lms](LMS APP)
I tried auto update and deployed in Firebase Hosting the 'list' directory but it's not working. When I open an old app it tells me it's already the last version despite showing the new number on the title for example:

![Screenshot 2023-03-10 alle 15 13 40](https://user-images.githubusercontent.com/32552589/224338140-9057f96f-3c94-47f3-b66c-8a6f07400202.png)

Another question: when I distribute the app to be downloaded I need to Notarise the app using Xcode and so then I can give it to be downloaded, but here it doesn't seem it's necessary, why?

**Comment by lijy91** [comment]
Can you try disabling the sandbox, and check the version number?

**Comment by kekko7072** [comment]
I can not disable sandbox otherwise my app will not work. Can you check the code in the link of the project ?

**Comment by wittDe** [comment]
The `sparkle:version` needs to correspond to their BundleVersion and needs to be a simple integer. Fill in `1.0.0` to `spark: shortVersionString`.

**Comment by kekko7072** [comment]
thanks @wittDe the sparkle:version is correct, but where should I put the tag `spark: shortVersionString` because on the example `appcast.xml` there isn't this field.

**Comment by kekko7072** [comment]
@wittDe this way is correct?
```
<item>
            <title>Version 1.0.0</title>
            <sparkle:shortVersionString>1.0.0</sparkle:shortVersionString>
            <pubDate>Mon, 10 Mar 2023 14:00:00 +0800</pubDate>
            <enclosure url="1.0.0+8/lms-1.0.0+8-macos.zip"
                sparkle:edSignature="XXX=="
                length="60672226"
                sparkle:version="1.0.0"
                sparkle:os="macos"
                type="application/octet-stream" />
        </item>
```

**Comment by kekko7072** [comment]
Thanks fixed.
