### ISSUE TITLE
Installation instructions incomplete?

### ISSUE THREAD

**Issue by D33pTh0ught** [leanflutter/auto_updater#44]
I have some problems following the instructions to get the sample to work (for windows).

1. I added the auto_updater package.
2. installed openssl
3. adjusted the `main.dart` according to the sample
4. generated the private key
5. adjusted the `Runner.rc` (even though it is kinda obvious, it would not hurt to mention that the `+` sign at the start of the lines should not be copied)
6. added the `distribute_options.yaml`
7. ran `flutter_distributor release --name dev --jobs release-windows` (the command does not work when using bash on windows, maybe a hint in the readme would be nice)

I now get the following error:
```
Successfully built Directory: 'build/windows/runner/Release' in 33s
PathNotFoundException: Cannot open file, path = 'windows/packaging/exe/make_config.yaml' (OS Error: The system cannot find the path specified.
, errno = 3)
```

After creating the missing file (according to this link: [distributor.leanflutter.org/docs/makers/exe](https://distributor.leanflutter.org/docs/makers/exe)), which is not mentioned in the readme, I still get the following error:
```
Successfully built Directory: 'build/windows/runner/Release' in 33s
Error on line 3, column 7: Mapping values are not allowed here. Did you miss a colon earlier?
  ╷
3 │ app_id: 5B599538-42B1-4826-A479-AF079F21A65D
  │       ^
  ╵
```

Any idea what I am doing wrong?

**Comment by sircambridge** [comment]
I followed the instructions until this point and I have the same problem.

turns out comments in .yaml is not //, but # - just remove the first two lines of comments in the example from  make_config.yaml

**Comment by lijy91** [comment]
Docs error fixed in https://github.com/leanflutter/flutter_distributor/commit/8311b4c8fef99d0b728bc5ded29de140afe84e76
