### ISSUE TITLE
【Windows】generate_keys.bat 文件路径错误

### ISSUE THREAD

**Issue by 15563988825** [leanflutter/auto_updater#5]
flutter pub run auto_updater:generate_keys报错，文件路径未找到
经查为generate_keys.bat关联路径错误

**错误的关联路径为**：  ..\Windows\WinSparkle-0.7.0\bin\generate_keys.bat

![fde12cf0a4b1790cff2d487ed8e7c35](https://user-images.githubusercontent.com/4360198/160226605-17859eb4-4bed-47d0-b92e-488b8a7cdcf7.png)

![293411e0939e580f4ca363bc47d161f](https://user-images.githubusercontent.com/4360198/160226610-da1ab792-614e-45a4-814c-69753d14341c.png)

**Comment by lijy91** [comment]
已修复，请更新到 0.1.3
