### ISSUE TITLE
后台检查更新未生效。

### ISSUE THREAD

**Issue by tangsj** [leanflutter/auto_updater#58]
autoUpdater.checkForUpdates(inBackground: false);   使用false时，在开发模式下启动应用程序会提示程序更新 。
![image](https://github.com/leanflutter/auto_updater/assets/4578080/3c8e37f7-a737-4779-95d7-fbc6b5e06ecd)
但是如果使用inBackground: true,  程序就不会有任何提示。 这是为何？

**Comment by tangsj** [comment]
升级Flutter后提示以下错误信息
[ERROR:flutter/shell/common/shell.cc(1015)] The 'auto_updater' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

当前flutter 版本
Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 41456452f2 (10 days ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5

**Comment by lijy91** [comment]
经测试只要同一个版本号被点击过忽略些版本，如果 inBackground 设为 true 时将不会有提示

**Comment by GolnazMirzaie** [comment]
@tangsj is your problem solved? I'm getting this error too! can it cause problem or it's ok to be ignored?

**Comment by vd3d** [comment]
Hi, I also got this error message. I don't know what to do with this ! Anyone find a way to solve it ?

Thanks
