### ISSUE TITLE
【Windows】靜默檢查更新

### ISSUE THREAD

**Issue by 15563988825** [leanflutter/auto_updater#6]
儅checkForUpdates調用時，
運行每次都會彈出檢查更新的對話框
![image](https://user-images.githubusercontent.com/4360198/160227307-441aad62-e3b8-4eae-9940-5e7d8283a78e.png)
是否可支持靜默狀態檢查更新？即不顯示檢查更新對話框，而只當存在更新時再對話框提醒用戶？
![image](https://user-images.githubusercontent.com/4360198/160227286-02311091-7994-442c-8070-d7253e0d3ebf.png)

**Comment by 15563988825** [comment]
我创建了一个PR
https://github.com/leanflutter/auto_updater/pull/8
在Windows平台新增了函数
checkForUpdatesWithoutUI()
用以静默检查更新

**Comment by lijy91** [comment]
已合并
