### ISSUE TITLE
Distribution Error with App Store Connect

### ISSUE THREAD

**Issue by ttzein6** [leanflutter/auto_updater#63]
I am encountering this error (check attached screenshot) when attempting to distribute my app using App Store Connect, even though I have enabled App Sandboxing.

I am using the auto_updater package to handle app updates for installations outside the App Store. However, I want to provide two download options:

	1.	Download the app from the App Store.
	2.	Download the app installer from the website.

Is there any solution or workaround for this issue to unblock me?

Thank you.
![image](https://github.com/user-attachments/assets/ecc44e42-82d2-4f62-b9b1-2a394567e612)

**Comment by BruceChen5683** [comment]
you need codesign these files.
 codesign --force --entitlements macos/Runner/Release.entitlements -s  "Developer ID Application:XXX" macos/Pods/Sparkle/Sparkle.framework/Versions/B/XPCServices/Downloader.xpc/Contents/MacOS/Downloader;
 codesign --force --entitlements macos/Runner/Release.entitlements -s  "Developer ID Application:XXX" macos/Pods/Sparkle/Sparkle.framework/Versions/B/XPCServices/Installer.xpc/Contents/MacOS/Installer;
 codesign --force --entitlements macos/Runner/Release.entitlements -s  "Developer ID Application:XXX" macos/Pods/Sparkle/Sparkle.framework/Versions/B/Updater.app/Contents/MacOS/Updater;
 codesign --force --entitlements macos/Runner/Release.entitlements -s  "Developer ID Application:XXX" macos/Pods/Sparkle/Sparkle.framework/Versions/B/Autoupdate;

**Comment by ttzein6** [comment]
Thank you @BruceChen5683 !
