### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by luyanggao** [leanflutter/auto_updater#9]
I operate according to the document and can download normally, but then I report an error：
更新错误！
更新未正确签名。

**Comment by lijy91** [comment]
请提供一下你的 appcast.xml 文件。

**Comment by luyanggao** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
    <channel>
        <title>auto_updater_example</title>
        <description>Most recent updates to auto_updater_example</description>
        <language>en</language>
        <item>
            <title>Version 1.2.2</title>
            <sparkle:releaseNotesLink>
                https://software.taxbook.zstax.com/taxbook/pc/windows/prod/source_package/release_notes.html
            </sparkle:releaseNotesLink>
            <pubDate>Thur, 31 Mar 2022 09:00:00 +0800</pubDate>
            <enclosure url="https://software.taxbook.zstax.com/taxbook/pc/windows/prod/source_exe/zstax_enterprise_edition.exe"
                       sparkle:version="1.2.2"
                       sparkle:edSignature="MEQCIG96SrR/6Mzfvm/Rl1LY+ZODGzZkKQDGxk0vz5ZttxfyAiBhGDjUiVMamBZPE+UQrmhFlHXLF0Agbvtn14EAvYU/Tw=="
                       sparkle:os="windows"
                       length="0"
                       type="application/octet-stream" />
        </item>
    </channel>
</rss>

**Comment by luyanggao** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
    <channel>
        <title>auto_updater_example</title>
        <description>Most recent updates to auto_updater_example</description>
        <language>en</language>
        <item>
            <title>Version 1.2.2</title>
            <sparkle:releaseNotesLink>
                https://software.taxbook.zstax.com/taxbook/pc/windows/prod/source_package/release_notes.html
            </sparkle:releaseNotesLink>
            <pubDate>Thur, 31 Mar 2022 09:00:00 +0800</pubDate>
            <enclosure url="https://software.taxbook.zstax.com/taxbook/pc/windows/prod/source_exe/zstax_enterprise_edition.exe"
                       sparkle:version="1.2.2"
                       sparkle:edSignature="MEQCIG96SrR/6Mzfvm/Rl1LY+ZODGzZkKQDGxk0vz5ZttxfyAiBhGDjUiVMamBZPE+UQrmhFlHXLF0Agbvtn14EAvYU/Tw=="
                       sparkle:os="windows"
                       length="0"
                       type="application/octet-stream" />
        </item>
    </channel>
</rss>
`

**Comment by lijy91** [comment]
把 `sparkle:edSignature` 改为 `sparkle:dsaSignature`，edSignature 为 macOS 使用，dsaSignature 为 Windows 使用

**Comment by luyanggao** [comment]
已解决。感谢！！
